### ISSUE TITLE
Starting tutorial

### ISSUE THREAD

**Issue by yarodevuci** [pyjamasam/DIYDragy#3]
@pyjamasam 
 Hi, could you please make a video tutorial, how to get started, showing your board connected with components and how to connect the assembled hardware to the board 
GPS has VCC not VDD (as on scheme) wire. Also does the BLE board needs to be reprogrammed? 
Finally how to change GPS refresh rate to 10HZ? 
Looks very cool.

**Comment by yarodevuci** [comment]
@pyjamasam are you there?

**Comment by pyjamasam** [comment]
In the case of my very quick schematic, the VDD pin is the same as the GPS hardware's VCC pin.  Looks like I just made a typo when I made the schematic.

The components are connected as per that schematic diagram.  Nothing fancy.  The BLE board does need a specific firmware programmed to it.  I have included the one I used in this repo (https://github.com/pyjamasam/DIYDragy/tree/master/nRF52), but looking back at things now, its more then possible to use something like PlatformIO to write an Ardunio framework based framework.  All the firmware does is bridge the uart and create a BLE serial connection.  Nothing else is done in the hardware.  The BLE connection is advertised as a uart.  The Phone software just sends and receives raw binary GPS commands.

As for switching the GPS to 10hz, you'll need to use u-center (https://www.u-blox.com/en/product/u-center)  and change the protocol to ubx and the rate to 10hz.  This video (https://www.youtube.com/watch?v=TwhCX0c8Xe0) has some info that should help a little with that).  Sorry I had left that information out of my details.

**Comment by yarodevuci** [comment]
Thank you! I have ordered needed parts that you listed and will try soon to put all together

**Comment by yarodevuci** [comment]
@pyjamasam are you on discord or any other platforms to better reach you?

**Comment by pyjamasam** [comment]
I am on discord as PyjamaSam#9955
